### ISSUE TITLE
Progress output from YaRadare is not valid JSON

### ISSUE THREAD

**Issue by ogarrett** [deepfence/YaRadare#25]
As YaRadare runs, it outputs progress information that appears to be JSON-formatted, but is not valid JSON.  A user could easily be confused into believing the output can be processed as JSON.

Compare the output from the following two invocations of YaRadare:

```
# Capture output to the terminal and save in /tmp/output-1.txt
docker run -i --rm --name=deepfence-yaradare -v /var/run/docker.sock:/var/run/docker.sock deepfenceio/deepfence-yaradare:latest --image-name node:latest > /tmp/output-1.txt

# Instruct YaRadare to save output to /tmp/output-2.txt
docker run -i --rm --name=deepfence-yaradare -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/home/deepfence/output deepfenceio/deepfence-yaradare:latest --image-name node:latest --json-filename=output-2.txt
```

`/tmp/output-2.txt` is valid JSON.

`/tmp/output-1.txt` appears to be JSON, but is instead a stream of JSON-like progress reports (where some values are not quoted), followed by an empty IOC list.

**Comment by deviprasad303** [comment]
raised a new PR to resolve it

**Comment by ogarrett** [comment]
Unfortunately, the output is still not valid JSON.

Test case:

```bash
docker pull node:latest

docker run -i --rm --name=deepfence-yaradare -v /var/run/docker.sock:/var/run/docker.sock deepfenceio/deepfence-yaradare:latest --image-name node:latest > /tmp/log.json

cat /tmp/log.json | jq '.IOC[] | ."Matched Rule Name"'
   parse error: Invalid numeric literal at line 10, column 26
```

Some notes:

 * Used `docker run -i` rather than `docker run -it` for reasons in #3 
 * Redirected output to file `/tmp/log.json` rather than piping directly to `jq` so you can inspect the output.  You get the same results if you pipe directly to `jq`

The invalid output includes the following yaml snippet:

```yaml
{
  "Timestamp": "2022-07-14 11:32:47.323984722 +00:00",
  "Image Name": "node:latest",
  "Image ID": "a67015ce5a53689bb1128ec114468a168684f795b6a480140eddb9bfff691102",
  "Malware match detected are": [
    {
      "Matched Rule Name": "spyeye_plugins",
      "Strings to match are":
            "config.dat",
      "Category": [banker],
      "File Name": "/tmp/Deepfence/YaRadare/df_nodelatest/ExtractedFiles/6a57181cdc0780bfbf41b0ee6a09d9d7f719ab7fbfddd910ee07f67d3f7099b3/etc/debconf.conf",
      "author": Jean-Philippe Teissier / @Jipe_
      "description": SpyEye X.Y Plugins memory
      "date": 2012-05-23
      "version": 1.0
      "filetype": memory
      "Summary": The file /tmp/Deepfence/YaRadare/df_nodelatest/ExtractedFiles/6a57181cdc0780bfbf41b0ee6a09d9d7f719ab7fbfddd910ee07f67d3f7099b3/etc/debconf.conf has a banker match.The matched rule file's  author  is Jean-Philippe Teissier / @Jipe_ .The file has a rule match that  SpyEye X.Y Plugins memory .The matched rule file's  date  is 2012-05-23 .The matched rule file's  version  is 1.0 .The matched rule file's  filetype  is memory .,
    } 
  ]
}
```

Note that many values are not quoted.
